# -*- coding: utf-8 -*-
"""1. tutorial-limpieza-datos - practica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lw3BV3-Y83waizuCwITWaOGfcD5bd8s9

# TUTORIAL: LIMPIEZA DE DATOS CON PYTHON Y PANDAS

# 1. El problema del negocio

Una entidad bancaria contrata a una empresa de marketing encargada de contactar telefónicamente a posibles clientes para determinar si están interesados o no en adquirir un certificado de depósito a término con el banco.

¿Qué perfil tienen los clientes con mayor potencial de conversión?

#2. El set de datos

La información recolectada por la empresa de mercadeo se encuentra en un archivo CSV (`dataset_banco.csv`) con 45215 filas y 17 columnas.

Cada registro contiene 16 características (las primeras 16 columnas) y una categoría ("yes" o "no" dependiendo de si la persona está o no interesada en adquirir el producto). Las columnas son:

1. "age":  edad (numérica)
2. "job": tipo de trabajo (categórica: "admin.", "unknown", "unemployed", "management", "housemaid", "entrepreneur", "student", "blue-collar","self-employed", "retired", "technician", "services")
3. "marital": estado civil (categórica: "married", "divorced", "single")
4. "education": nivel educativo (categórica: "unknown", "secondary", "primary", "tertiary")
5. "default": si dejó de pagar sus obligaciones (categórica: "yes", "no")
6. "balance": saldo promedio anual en euros (numérica)
7. "housing": ¿tiene o no crédito hipotecario? (categórica: "yes", "no")
8. "loan": ¿tiene créditos de consumo? (categórica: "yes", "no")
9. "contact": medio a través del cual fue contactado (categórica: "unknown", "telephone", "cellular")
10. "day": último día del mes en el que fue contactada (numérica)
11. "month": último mes en el que fue contactada (categórica: "jan", "feb", "mar", ..., "nov", "dec")
12. "duration": duración (en segundos) del último contacto (numérica)
13. "campaign": número total de veces que fue contactada durante la campaña (numérica)
14. "pdays": número de días transcurridos después de haber sido contactado antes de la campaña actual (numérica. -1 indica que no fue contactado previamente)
15. "previous": número de veces que ha sido contactada antes de esta campaña (numérica)
16. "poutcome": resultado de la campaña de marketing anterior (categórica: "unknown", "other", "failure", "success")
17. "y": categoría ¿el cliente se suscribió a un depósito a término? (categórica: "yes", "no")

#3. Una primera mirada al dataset
"""

# Importar librerías
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Lectura
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
ruta = "dataset_banco.csv"
data = pd.read_csv(ruta)

from google.colab import drive
drive.mount('/content/drive')

print(data.shape) # dimensiones del DataFrame.
data.head()

# Veamos las variables categóricas y las numéricas
data.info() #resumen conciso sobre el DataFrame

"""#4. Limpieza

Realizaremos el proceso de limpieza teniendo en cuenta las situaciones más comunes:

1. Datos faltantes en algunas celdas
2. Columnas irrelevantes (que no responden al problema que queremos resolver)
3. Registros (filas) repetidos
4. Valores extremos (*outliers*) en el caso de las variables numéricas. Se deben analizar en detalle pues no necesariamente la solución es eliminarlos
5. Errores tipográficos en el caso de las variables categóricas

Al final de este proceso de limpieza deberíamos tener un set de datos **íntegro**, listo para la fase de Análisis Exploratorio.

## 4.1 Datos faltantes

Acá comenzamos a ver que los datos no están completos, pues no todas las columnas tienen la misma cantidad de registros.

El número total de registros debería ser 45.215. Sin embargo columnas como "job", "marital", "education", "balance", "duration" y "pdays".

Por ser tan pocos los datos  faltantes optaremos por eliminar las filas correspondientes:
"""

data.info()

"""##4.2 Columnas irrelevantes

Una columna irrelevante puede ser:

- **Una columna que no contiene información relevante para el problema que queremos resolver**. Por ejemplo en este caso podría ser una columna que no guarde relación con el posible perfil del cliente (deporte favorito, hobbies, comida favorita, etc.)
- **Una columna categórica pero con un sólo nivel**. Por ejemplo si en la columna "job" solo tuviésemos el nivel "unknown".
- **Una columna numérica pero con un sólo valor**. Por ejemplo si en la columna "edad" todos los vlaores fuesen iguales a 50.
- **Columnas con información redundante**. Por ejemplo si además de las columnas "month" y "day" tuviésemos la columna "month-day", resultado de combinar las dos anteriores.

Si tenemos la duda de si alguna columna puede ser relevante o no lo mejor es dejarla (y más adelante en posteriores etapas podremos darnos cuenta de si se debe preservar o no).

En este caso todas las columnas pueden resultar relevantes, pero debemos verificar que no haya columnas categóricas con un sólo nivel, o columnas numéricas con un sólo valor:
"""

# Conteo de los niveles en las diferentes columnas categóricas

categorical_cols = data.select_dtypes(include=['object']).columns  # recordar que para las variables categoricas se usa "object"
for col in categorical_cols:
    num_levels = data[col].nunique() #remember - this line is to count unique values and tell if there are categorical columns with only one level
    print(f"Column '{col}' has {num_levels} unique levels.")

"""Todas las columnas categóricas tienen más de 1 subnivel. No eliminaremos ninguna.

Verifiquemos lo que ocurre con las columnas numéricas:
"""

# Estadistica descriptiva
numerical_cols = data.select_dtypes(include=['number']).columns
for i in numerical_cols:
  desvest = data[i].std()
  print(f"standard deviation of {col} is = {desvest}")

"""Todas las columnas numéricas tienen desviaciones estándar ("std") diferentes de cero, lo que indica que no tienen un único valor.

Preservaremos todas las columnas numéricas.

##4.3 Filas repetidas
"""

print(f'Tamaño del set antes de eliminar las filas repetidas: {data.shape}')
data.drop_duplicates(inplace=True)
print(f'Tamaño del set después de eliminar las filas repetidas: {data.shape}')

"""##4.4 *Outliers* en las variables numéricas

No siempre se deben eliminar los *outliers* porque dependiendo de la variable numérica analizada estos pueden contener información importante.

Creemos gráficas tipo "boxplot" de las columnas numéricas:
"""

print(data.shape) # dimensiones del DataFrame.
data.head()

# Generar gráficas individuales pues las variables numéricas
# están en rangos diferentes
numerical_cols =data.select_dtypes(include = ['number']).columns
for col in numerical_cols:
  plt.figure(figsize=(6,4))
  sns.boxplot(data[col]) # allows to analyze distribution of numerical data
  plt.title(f'{col} boxplot')
  plt.show()

"""**Observaciones:**
- "age": hay sujetos con edades mucho mayores a 100 años
- "duration": hay valores negativos
- "previous": hay un valor extremadamente alto (cercano a 300)
"""

# Eliminar filas con "age">100
data = data[data['age'] < 100]

# Eliminar filas con "duration"<0
data = data[data['duration'] > 0]

# Eliminar filas con "previous">100
data=data[data['previous'] < 100]

"""##4.5 Errores tipográficos en variables categóricas

En una variable categórica pueden aparecer sub-niveles como "unknown" y "UNK" que para nosotros son equivalentes pero que para nuestro programa parecerían diferentes.

Se deben unificar estos sub-niveles
"""



# Graficar los subniveles de cada variable categórica
variable_categorica= data.select_dtypes(include =['object']).columns
for col in variable_categorica:
  plt.figure(figsize=(6, 4))  # Adjust figure size as needed
  sns.countplot(x=col, data=data)  #con seaborn




  plt.title(f'Distribution of {col}')
  plt.xticks(rotation=45, ha='right')
  plt.tight_layout()
  plt.show()

"""Inicialmente se observa que hay sub-niveles con el mismo nombre pero escritos en minúscula, en mayúscula o con la primera letra en mayúscula.

Unifiquemos estos sub-niveles inicialmente:
"""



# job: unificar admin. y administrative
data['job'] = data['job'].replace(['admin.'],'administrative')

data['job'] = data['job'].replace(['UNK'], 'unknown')
display (data)

# marital: unificar div. y divorced
data['marital']=data['marital'].replace(['div.'], 'divorced')

# education: unificar sec. y secondary, unk y unknown
data['education']=data['education'].replace(['sec.'], 'secondary')
data['education'] = data['education'].replace(['unk'], 'unknown')

# contact: unificar telephone y phone
data['contact'] =data['contact'].replace(['telephone'], 'phone')

# poutcome: unificar unk y unknown

data['poutcome'] =data['poutcome'].replace(['UNK'],'unknown')

data.shape

"""¡Y listo, ya hemos realizado la limpieza de nuestro set de datos!

Originalmente tenía 45.215 registros y 17 columnas. El dataset resultante tiene 45.189 filas (26 menos) y 17 columnas.

El set de datos ya está listo para el Análisis Exploratorio.
"""

# Crear nuevo archivo csv a partir de dataframe
ruta = "dataset_banco_clean.csv"
data.to_csv(ruta, index=False)